Get levels
ioana637/jobs-server pull request #5
Opened 2018-11-18 18:09 UTC by GhimpuLucianEduard

**Endpoit**: `/ability/levels`

2018-11-18 18:10 UTC, GhimpuLucianEduard commented on src/main/java/com/ubb/jobs/model/Level.java
> +    public String getLevelName() { return levelName; }
A fost singura metoda simpla pe care am gasit-o ca sa pot serializa enum-ul mai dragut fara sa mai fac dto si mapper.

2018-11-19 07:11 UTC, Sinars requested changes

2018-11-19 07:11 UTC, Sinars commented on src/main/java/com/ubb/jobs/model/Level.java
> +    public String getLevelName() { return levelName; }
vezi ca ai facut un typo la independent "independet", in rest pare inregula. Ai si testat?

2018-11-19 07:11 UTC, Sinars commented on src/main/java/com/ubb/jobs/model/Level.java
> +    public String getLevelName() { return levelName; }
m-am uitat acum pe postare, mai rezolva doar typo-ul si dupa poti sa faci merge

2018-11-19 08:14 UTC, GhimpuLucianEduard commented
@Sinars fixed in 57a85ef4449d8ca02f50c48c04cef1ab3b8e72fc.

2018-11-19 08:14 UTC, merged